import express from 'express'
import pg from 'pg'
import { readFileSync } from 'node:fs'
import { cert, getApps, initializeApp } from 'firebase-admin/app'
import { getAuth } from 'firebase-admin/auth'
import { createMarketData } from './services/market-data.mjs'
import { createEvidenceIngestion } from './services/evidence-ingestion.mjs'
import { attentionScore } from './services/attention-score.mjs'
import { rateLimit } from './middleware/rate-limit.mjs'

const app = express(), port = Number(process.env.PORT || process.env.API_PORT || 8787)
app.use(express.json({ limit: '32kb' }))
app.use((_, res, next) => { res.setHeader('Access-Control-Allow-Origin', process.env.FRONTEND_URL || 'http://localhost:5173'); res.setHeader('Access-Control-Allow-Headers', 'Authorization, Content-Type, X-Demo-User'); next() })
const db = process.env.DATABASE_URL ? new pg.Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_SSL === 'false' ? false : { rejectUnauthorized: false } }) : null
// Redis is intentionally not part of the MVP runtime. PostgreSQL is authoritative;
// the service interfaces accept a null cache so Redis can be introduced at scale.
const cache = null
let firebaseAuth = null
try { const rawServiceAccount = process.env.FIREBASE_SERVICE_ACCOUNT_JSON || (process.env.FIREBASE_SERVICE_ACCOUNT_PATH ? readFileSync(process.env.FIREBASE_SERVICE_ACCOUNT_PATH, 'utf8') : ''); if (rawServiceAccount) { const serviceAccount = JSON.parse(rawServiceAccount); if (!getApps().length) initializeApp({ credential: cert(serviceAccount) }); firebaseAuth = getAuth() } } catch { console.warn('Firebase Admin is not configured; demo auth is enabled.') }

async function cached(key, seconds, action) { const hit = await cache?.get(key); if (hit) return JSON.parse(hit); const value = await action(); await cache?.set(key, JSON.stringify(value), { EX: seconds }); return value }
async function requireUser(req, res, next) {
  try {
    const token = req.headers.authorization?.replace('Bearer ', '')
    const identity = token && firebaseAuth ? await firebaseAuth.verifyIdToken(token) : { uid: req.header('x-demo-user') || 'demo-user', email: 'demo@marketmemory.app', name: 'Demo User', picture: null }
    if (!db) return res.status(503).json({ error: 'Database is not configured. Set DATABASE_URL.' })
    const { rows } = await db.query(`INSERT INTO users(firebase_uid,email,name,avatar_url) VALUES($1,$2,$3,$4) ON CONFLICT(firebase_uid) DO UPDATE SET email=EXCLUDED.email, name=COALESCE(EXCLUDED.name,users.name) RETURNING *`, [identity.uid, identity.email || null, identity.name || identity.email || 'Investor', identity.picture || null])
    req.user = rows[0]; next()
  } catch { res.status(401).json({ error: 'Your Firebase session is invalid.' }) }
}
const market = createMarketData({ cache, twelveDataKey: process.env.TWELVE_DATA_API_KEY })
const { quote, search: marketSearch, twelve, yahoo } = market
const evidenceIngestion = createEvidenceIngestion({ db, newsApiKey: process.env.GNEWS_API_KEY })
async function upsertStock(item) { const { rows } = await db.query(`INSERT INTO stocks(symbol,company_name,exchange) VALUES($1,$2,$3) ON CONFLICT(symbol) DO UPDATE SET company_name=EXCLUDED.company_name, exchange=EXCLUDED.exchange, updated_at=now() RETURNING *`, [item.symbol, item.name, item.exchange]); return rows[0] }
async function detectMovement(stock, market) { const move = Math.abs(Number(market.change)); if (move < 0.25) return; const recent = await db.query(`SELECT id FROM events WHERE stock_id=$1 AND event_type='MARKET_MOVEMENT' AND timestamp > now() - interval '4 hours' LIMIT 1`, [stock.id]); if (recent.rowCount) return; const direction = Number(market.change) >= 0 ? 'rose' : 'fell'; const importance = attentionScore(move); const { rows } = await db.query(`INSERT INTO events(stock_id,event_type,title,description,importance,status) VALUES($1,'MARKET_MOVEMENT',$2,$3,$4,'DETECTED') RETURNING id`, [stock.id, `${stock.symbol} ${direction} ${move.toFixed(2)}%`, 'A market-data movement was detected. We are waiting for verified evidence before assigning a reason.', importance]); const eventId = rows[0].id; try { await evidenceIngestion.enrichEvent({ eventId, companyName: stock.company_name }) } catch (error) { console.warn('Evidence ingestion skipped:', error.message) } if (importance >= 60) await db.query(`INSERT INTO notifications(user_id,event_id,type) SELECT user_id,$1,'IN_APP' FROM watchlist_items WHERE stock_id=$2 AND removed_at IS NULL ON CONFLICT DO NOTHING`, [eventId, stock.id]); if (importance >= 80) await cache?.set(`hot-event:${stock.symbol}`, JSON.stringify({ eventId, importance }), { EX: 900 }) }

app.get('/api/health', (_, res) => res.json({ database: Boolean(db), firebase: Boolean(firebaseAuth), cache: 'Not enabled in MVP; Redis is a documented scale-up path.', marketProvider: process.env.TWELVE_DATA_API_KEY ? 'Twelve Data' : 'Yahoo Finance (development fallback)' }))
app.get('/api/search', requireUser, async (req, res) => { try { const q = String(req.query.q || '').trim(); if (q.length < 2) return res.json([]); res.json(await cached(`search:${q.toLowerCase()}`, 300, () => marketSearch(q))) } catch (error) { res.status(502).json({ error: error.message }) } })
app.get('/api/stocks/:symbol', requireUser, async (req, res) => { try { const symbol = req.params.symbol, current = await quote(symbol); if (process.env.TWELVE_DATA_API_KEY) { const series = await twelve('time_series', { symbol, interval: '1day', outputsize: '30' }); return res.json({ ...current, history: (series.values || []).reverse().map(v => ({ time: v.datetime, price: Number(v.close) })) }) } const chart = await yahoo(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=1mo&interval=1d`), result = chart.chart?.result?.[0], closes = result?.indicators?.quote?.[0]?.close || []; return res.json({ ...current, history: closes.map((price, i) => ({ time: new Date(result.timestamp[i] * 1000).toISOString(), price })).filter(x => x.price) }) } catch (error) { res.status(502).json({ error: error.message }) } })
app.get('/api/profile', requireUser, async (req, res) => { const history = await db.query(`SELECT s.symbol,s.company_name,w.added_at,w.removed_at FROM watchlist_items w JOIN stocks s ON s.id=w.stock_id WHERE w.user_id=$1 ORDER BY COALESCE(w.removed_at,w.added_at) DESC`, [req.user.id]); res.json({ user: req.user, history: history.rows }) })
app.patch('/api/profile/preferences', requireUser, async (req, res) => { const { rows } = await db.query(`UPDATE users SET preferences = preferences || $2::jsonb WHERE id=$1 RETURNING preferences`, [req.user.id, JSON.stringify(req.body || {})]); res.json(rows[0].preferences) })
app.get('/api/watchlist', requireUser, async (req, res) => { const { rows } = await db.query(`SELECT s.*,w.added_at,w.last_seen_at FROM watchlist_items w JOIN stocks s ON s.id=w.stock_id WHERE w.user_id=$1 AND w.removed_at IS NULL ORDER BY w.added_at DESC`, [req.user.id]); const result = await Promise.all(rows.map(async s => { try { const market = await quote(s.symbol); await db.query('INSERT INTO price_snapshots(stock_id,price,change_percent,source) VALUES($1,$2,$3,$4)', [s.id, market.price, market.change, 'Yahoo Finance']); await detectMovement(s, market); return { ...s, ...market, delayed: false } } catch { const last = await db.query('SELECT price,change_percent,timestamp FROM price_snapshots WHERE stock_id=$1 ORDER BY timestamp DESC LIMIT 1', [s.id]); return { ...s, price: Number(last.rows[0]?.price || 0), change: Number(last.rows[0]?.change_percent || 0), delayed: true } } })); await db.query('UPDATE watchlist_items SET last_seen_at=now() WHERE user_id=$1 AND removed_at IS NULL', [req.user.id]); res.json(result) })
app.get('/api/discover', requireUser, async (req, res) => { const suffix = process.env.TWELVE_DATA_API_KEY ? ':NSE' : '.NS'; const catalog = [
  { symbol: `INFY${suffix}`, reason: 'IT services · similar to TCS' }, { symbol: `HCLTECH${suffix}`, reason: 'IT services · large-cap peer' }, { symbol: `WIPRO${suffix}`, reason: 'IT services · sector exploration' },
  { symbol: `ICICIBANK${suffix}`, reason: 'Private bank · similar to HDFC Bank' }, { symbol: `KOTAKBANK${suffix}`, reason: 'Private bank · sector exploration' }, { symbol: `SBIN${suffix}`, reason: 'Banking · market exploration' },
  { symbol: `MARUTI${suffix}`, reason: 'Auto · similar to Tata Motors' }, { symbol: `M&M${suffix}`, reason: 'Auto · sector exploration' }, { symbol: `SUNPHARMA${suffix}`, reason: 'Healthcare · market exploration' }, { symbol: `BHARTIARTL${suffix}`, reason: 'Telecom · market exploration' }
]; const watched = await db.query(`SELECT s.symbol FROM watchlist_items w JOIN stocks s ON s.id=w.stock_id WHERE w.user_id=$1 AND w.removed_at IS NULL`, [req.user.id]); const watchedSymbols = new Set(watched.rows.map(row => row.symbol)); const results = await Promise.allSettled(catalog.filter(item => !watchedSymbols.has(item.symbol)).map(async item => ({ ...(await quote(item.symbol)), reason: item.reason }))); const stocks = results.filter(result => result.status === 'fulfilled').map(result => result.value); res.json({ similar: stocks.filter(stock => stock.reason.includes('similar') || stock.reason.includes('peer')), explore: stocks.filter(stock => stock.reason.includes('exploration')) }) })
app.post('/api/watchlist', requireUser, async (req, res) => { try { const market = await quote(String(req.body.symbol || '').trim().toUpperCase()); const stock = await upsertStock(market); const { rows } = await db.query(`INSERT INTO watchlist_items(user_id,stock_id,removed_at,added_at) VALUES($1,$2,NULL,now()) ON CONFLICT(user_id,stock_id) DO UPDATE SET removed_at=NULL,added_at=now() RETURNING *`, [req.user.id, stock.id]); await db.query('INSERT INTO price_snapshots(stock_id,price,change_percent,source) VALUES($1,$2,$3,$4)', [stock.id, market.price, market.change, 'Yahoo Finance']); await detectMovement(stock, market); res.status(201).json({ ...stock, ...market, watchlist: rows[0] }) } catch (error) { res.status(400).json({ error: error.message }) } })
app.delete('/api/watchlist/:symbol', requireUser, async (req, res) => { const result = await db.query(`UPDATE watchlist_items w SET removed_at=now() FROM stocks s WHERE w.stock_id=s.id AND w.user_id=$1 AND s.symbol=$2 AND w.removed_at IS NULL RETURNING w.id`, [req.user.id, req.params.symbol]); if (!result.rowCount) return res.status(404).json({ error: 'Stock is not in your watchlist.' }); res.status(204).end() })
app.get('/api/feed', requireUser, async (req, res) => { await db.query(`UPDATE events SET archived_at=now() WHERE archived_at IS NULL AND timestamp < now() - interval '5 hours'`); const query = `SELECT e.*,s.symbol,s.company_name,ues.seen_at,COALESCE(json_agg(json_build_object('source',ev.source,'url',ev.source_url,'confidence',ev.confidence)) FILTER (WHERE ev.id IS NOT NULL),'[]') evidence FROM events e JOIN stocks s ON s.id=e.stock_id JOIN watchlist_items w ON w.stock_id=s.id LEFT JOIN evidence ev ON ev.event_id=e.id LEFT JOIN user_event_state ues ON ues.event_id=e.id AND ues.user_id=$1 WHERE w.user_id=$1 AND w.removed_at IS NULL AND e.archived_at IS NULL GROUP BY e.id,s.symbol,s.company_name,ues.seen_at ORDER BY e.timestamp DESC LIMIT 30`; let { rows } = await db.query(query, [req.user.id]); await Promise.all(rows.filter(e => e.status === 'DETECTED').map(async e => { try { await evidenceIngestion.enrichEvent({ eventId: e.id, companyName: e.company_name }) } catch { /* Unknown is an honest supported state. */ } })); ({ rows } = await db.query(query, [req.user.id])); res.json(rows.map(e => ({ ...e, verified: e.evidence.length > 0, reason: e.evidence.length ? e.description : 'We detected an unusual movement but found no verified reason yet. We’ll update this when reliable information becomes available.' }))) })
app.get('/api/history', requireUser, async (req, res) => { const { rows } = await db.query(`SELECT e.*,s.symbol,s.company_name FROM events e JOIN stocks s ON s.id=e.stock_id JOIN watchlist_items w ON w.stock_id=s.id WHERE w.user_id=$1 AND e.archived_at IS NOT NULL ORDER BY e.archived_at DESC LIMIT 50`, [req.user.id]); res.json(rows) })
app.get('/api/notifications', requireUser, async (req, res) => { const { rows } = await db.query(`SELECT n.*,e.title,e.description,s.symbol FROM notifications n JOIN events e ON e.id=n.event_id JOIN stocks s ON s.id=e.stock_id WHERE n.user_id=$1 ORDER BY n.created_at DESC LIMIT 30`, [req.user.id]); res.json(rows) })
app.post('/api/notifications/read', requireUser, async (req, res) => { await db.query(`UPDATE notifications SET status='READ',read_at=now() WHERE user_id=$1 AND status='UNREAD'`, [req.user.id]); res.status(204).end() })
app.post('/api/feed/seen', requireUser, async (req, res) => { await db.query(`INSERT INTO user_event_state(user_id,event_id,seen_at) SELECT $1,e.id,now() FROM events e JOIN watchlist_items w ON w.stock_id=e.stock_id WHERE w.user_id=$1 AND w.removed_at IS NULL ON CONFLICT(user_id,event_id) DO UPDATE SET seen_at=now()`, [req.user.id]); res.status(204).end() })
app.post('/api/explain', requireUser, rateLimit({ cache, limit: 5, windowSeconds: 86400 }), async (req, res) => { const event = req.body.event, question = String(req.body.question || '').trim(); if (!event?.id) return res.status(400).json({ error: 'event.id is required' }); const evidence = await db.query('SELECT source,source_url,published_at,confidence FROM evidence WHERE event_id=$1', [event.id]); if (!question) return res.json({ answer: evidence.rowCount ? 'Verified source links and timestamps are shown below. Ask a specific follow-up if you want a concise explanation of this evidence.' : 'No verified catalyst has been identified yet. We deliberately do not speculate.', cached: false, usedLlm: false }); if (!evidence.rowCount) return res.json({ answer: 'No verified catalyst has been identified yet, so there is nothing reliable for the assistant to explain.', cached: false, usedLlm: false }); const questionType = `q:${question.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim().slice(0, 80)}`; const existing = await db.query('SELECT answer FROM event_explanations WHERE event_id=$1 AND question_type=$2', [event.id, questionType]); if (existing.rowCount) return res.json({ answer: existing.rows[0].answer, cached: true, usedLlm: true }); if (!process.env.GROQ_API_KEY) return res.status(503).json({ error: 'GROQ_API_KEY is not configured.' }); const groq = await fetch('https://api.groq.com/openai/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${process.env.GROQ_API_KEY}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ model: 'qwen/qwen3.8-27b', temperature: 0, max_tokens: 180, messages: [{ role: 'system', content: 'Answer the question using only supplied verified evidence. Never infer causality, add facts, forecast, or give investment advice. If evidence cannot answer the question, say so. Under 90 words.' }, { role: 'user', content: JSON.stringify({ question, event, evidence: evidence.rows }) }] }) }); if (!groq.ok) return res.status(502).json({ error: 'Groq is temporarily unavailable.' }); const data = await groq.json(), answer = data.choices?.[0]?.message?.content; if (!answer) return res.status(502).json({ error: 'Groq returned no answer. Please retry.' }); await db.query('INSERT INTO event_explanations(event_id,question_type,question_text,answer) VALUES($1,$2,$3,$4) ON CONFLICT(event_id,question_type) DO NOTHING', [event.id, questionType, question, answer]); res.json({ answer, cached: false, usedLlm: true }) })
app.use((error, _, res, __) => { console.error(error); res.status(500).json({ error: 'Unexpected server error.' }) })
app.listen(port, '0.0.0.0', () => console.log(`API listening on port ${port}`))