/** Provider adapter: Twelve Data is primary for NSE; Yahoo is a development fallback. */
export function createMarketData({ cache, twelveDataKey }) {
  const cached = async (key, seconds, action) => { const hit = await cache?.get(key); if (hit) return JSON.parse(hit); const value = await action(); await cache?.set(key, JSON.stringify(value), { EX: seconds }); return value }
  const yahoo = async url => { const response = await fetch(url, { headers: { 'User-Agent': 'Mozilla/5.0 MarketMemory/1.0' } }); if (!response.ok) throw new Error('Market provider is unavailable'); return response.json() }
  const twelve = async (path, params) => { const url = new URL(`https://api.twelvedata.com/${path}`); Object.entries({ ...params, apikey: twelveDataKey }).forEach(([key, value]) => url.searchParams.set(key, value)); const response = await fetch(url), data = await response.json(); if (!response.ok || data.status === 'error') throw new Error(data.message || 'Twelve Data is unavailable'); return data }
  const quote = symbol => cached(`quote:${symbol}`, 30, async () => { if (twelveDataKey) { const q = await twelve('quote', { symbol }); return { symbol: q.symbol, name: q.name || q.symbol, price: Number(q.close), change: Number(q.percent_change || 0), currency: q.currency || 'INR', exchange: q.exchange || 'NSE' } } const data = await yahoo(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=1d&interval=1m`), q = data.chart?.result?.[0]?.meta; if (!q?.regularMarketPrice) throw new Error('No current quote available'); const previous = q.chartPreviousClose || q.previousClose || q.regularMarketPrice; return { symbol: q.symbol, name: q.longName || q.shortName || q.symbol, price: q.regularMarketPrice, change: ((q.regularMarketPrice - previous) / previous) * 100, currency: q.currency, exchange: q.exchangeName || '' } })
  const search = query => cached(`search:${query.toLowerCase()}`, 300, async () => { if (twelveDataKey) { const data = await twelve('symbol_search', { symbol: query }); return (data.data || []).filter(x => x.exchange === 'NSE' || x.country === 'India').slice(0, 8).map(x => ({ symbol: x.symbol.includes(':') ? x.symbol : `${x.symbol}:NSE`, name: x.instrument_name || x.symbol, exchange: x.exchange || 'NSE', type: 'EQUITY' })) } const data = await yahoo(`https://query1.finance.yahoo.com/v1/finance/search?q=${encodeURIComponent(query)}&quotesCount=8&newsCount=0`); return (data.quotes || []).filter(x => x.quoteType === 'EQUITY').map(x => ({ symbol: x.symbol, name: x.longname || x.shortname || x.symbol, exchange: x.exchDisp || '', type: x.quoteType })) })
  return { quote, search, twelve, yahoo }
}
