import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Bell, Bookmark, ChevronRight, CircleHelp, Compass, LogOut, Moon, MoreHorizontal, Plus, Search, Settings, Sparkles, Sun, TrendingDown, TrendingUp, X } from 'lucide-react'
import { onAuthStateChanged, signInWithPopup, signOut, type User } from 'firebase/auth'
import { auth, firebaseEnabled, googleProvider } from './firebase'
import './style.css'
import './product.css'

type Stock = { symbol: string; name: string; price: number; change: number; color: string; spark: number[]; delayed?: boolean; reason?: string }
type Event = { id: string | number; symbol: string; time: string; title: string; text: string; score: number; source?: string; verified: boolean; tag: string }

const allStocks: Stock[] = [
  { symbol: 'RELIANCE', name: 'Reliance Industries', price: 2947.35, change: 1.86, color: '#507be8', spark: [42,43,42,45,44,47,46,51,50,53,54,55] },
  { symbol: 'TCS', name: 'Tata Consultancy Services', price: 4032.10, change: -0.72, color: '#d27862', spark: [55,53,52,54,50,48,47,46,45,44,45,43] },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', price: 1719.60, change: 2.34, color: '#4b9d7a', spark: [35,37,36,38,42,40,44,43,48,47,50,53] },
  { symbol: 'INFY', name: 'Infosys', price: 1526.45, change: 0.48, color: '#9971c9', spark: [42,43,42,44,43,44,44,45,44,45,46,46] },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', price: 976.80, change: 3.12, color: '#da9f40', spark: [30,29,33,31,35,34,37,39,42,41,45,49] },
]

const events: Event[] = [
  { id: 1, symbol: 'HDFCBANK', time: 'Today, 10:42 AM', title: 'HDFC Bank is up 2.34%', text: 'The move follows a stronger-than-expected quarterly business update. Reported by 3 reliable sources.', score: 94, source: 'NSE filing + 2 sources', verified: true, tag: 'High attention' },
  { id: 2, symbol: 'RELIANCE', time: 'Today, 9:18 AM', title: 'Reliance gained 1.86%', text: 'A sector-wide energy rally is contributing to the move. The stock is outperforming its sector by 0.9%.', score: 73, source: 'Market data', verified: true, tag: 'Worth a look' },
  { id: 3, symbol: 'TCS', time: 'Yesterday, 3:31 PM', title: 'TCS slipped 0.72%', text: 'We detected an unusual move, but no verified reason has been found yet. We’ll update this when reliable information becomes available.', score: 64, verified: false, tag: 'Watching' },
]

function Sparkline({ values, color }: { values: number[]; color: string }) {
  const min = Math.min(...values), max = Math.max(...values)
  const points = values.map((v, i) => `${i * (100 / (values.length - 1))},${34 - ((v - min) / (max - min || 1)) * 28}`).join(' ')
  return <svg className="spark" viewBox="0 0 100 38" preserveAspectRatio="none"><polyline points={points} fill="none" stroke={color} strokeWidth="2.5" vectorEffect="non-scaling-stroke" /></svg>
}

function PriceHistoryChart({ history, change }: { history: { time: string; price: number }[]; change: number }) {
  const values = history.map(x => x.price).filter(Number.isFinite)
  if (values.length < 2) return <div className="chart-loading">Historical prices are unavailable right now.</div>
  const min = Math.min(...values), max = Math.max(...values), range = max - min || 1, base = values[0]
  const points = values.map((value, index) => `${38 + index * (242 / (values.length - 1))},${16 + (1 - (value - min) / range) * 108}`).join(' ')
  return <div className="price-chart"><div className="chart-label top">₹{max.toLocaleString('en-IN', { maximumFractionDigits: 0 })} · {((max / base - 1) * 100).toFixed(1)}%</div><div className="chart-label bottom">₹{min.toLocaleString('en-IN', { maximumFractionDigits: 0 })} · {((min / base - 1) * 100).toFixed(1)}%</div><svg viewBox="0 0 300 145" preserveAspectRatio="none"><line x1="38" y1="16" x2="280" y2="16"/><line x1="38" y1="70" x2="280" y2="70"/><line x1="38" y1="124" x2="280" y2="124"/><polyline points={points} fill="none" stroke={change >= 0 ? '#00a77c' : '#dd675d'} strokeWidth="3" vectorEffect="non-scaling-stroke"/></svg><div className="chart-axis"><span>{history[0].time.slice(5, 10)}</span><span>Today</span></div></div>
}

function Rupee({ value }: { value: number }) { return <>₹{value.toLocaleString('en-IN', { minimumFractionDigits: 2 })}</> }

function App() {
  const [watchlist, setWatchlist] = useState<Stock[]>(() => { try { const saved = localStorage.getItem('market-memory-watchlist'); return saved ? JSON.parse(saved) : allStocks.slice(0, 4) } catch { return allStocks.slice(0, 4) } })
  const [tab, setTab] = useState<'watchlist' | 'away' | 'discover' | 'profile'>('watchlist')
  const [search, setSearch] = useState('')
  const [selected, setSelected] = useState<Event | null>(null)
  const [explaining, setExplaining] = useState(false)
  const [explanation, setExplanation] = useState('')
  const [question, setQuestion] = useState('')
  const [filtered, setFiltered] = useState<Stock[]>([])
  const [feed, setFeed] = useState(events)
  const [unseenActivity, setUnseenActivity] = useState(events.length)
  const [user, setUser] = useState<User | null>(null)
  const [apiReady, setApiReady] = useState(false)
  const [signInError, setSignInError] = useState('')
  const [discoverStocks, setDiscoverStocks] = useState<{ similar: Stock[]; explore: Stock[] }>({ similar: allStocks.slice(1, 3), explore: allStocks.slice(3) })
  const [searchMessage, setSearchMessage] = useState('')
  const [discoverQuery, setDiscoverQuery] = useState('')
  const [dark, setDark] = useState(localStorage.getItem('market-memory-theme') === 'dark')
  const [stockDetail, setStockDetail] = useState<{ stock: Stock; history: { time: string; price: number }[] } | null>(null)
  const [authResolved, setAuthResolved] = useState(!firebaseEnabled)
  const [enteredApp, setEnteredApp] = useState(false)
  const [loading, setLoading] = useState(false)
  const [notice, setNotice] = useState('')
  const [notifications, setNotifications] = useState<any[]>([])
  const [showNotifications, setShowNotifications] = useState(false)
  const [showHelp, setShowHelp] = useState(false)
  const headers = async () => ({ 'Content-Type': 'application/json', ...(user ? { Authorization: `Bearer ${await user.getIdToken()}` } : { 'X-Demo-User': 'demo-user' }) })
  const stockFromApi = (s: any): Stock => ({ symbol: s.symbol, name: s.name || s.company_name, price: Number(s.price), change: Number(s.change), delayed: s.delayed, reason: s.reason, color: ['#507be8','#4b9d7a','#9971c9','#da9f40'][s.symbol.length % 4], spark: [35,38,37,40,39,42,41,45,44,47,46,49] })
  const loadWatchlist = async () => { setLoading(true); try { const r = await fetch('/api/watchlist', { headers: await headers() }); if (!r.ok) throw new Error(); const data = await r.json(); if (data.length) setWatchlist(data.map(stockFromApi)); setApiReady(true); setNotice(data.length ? 'Market data refreshed.' : 'Your watchlist is ready — search and add a stock to begin.') } catch { setApiReady(false); setNotice('Showing saved watchlist. Live market connection will retry.') } finally { setLoading(false) } }
  const loadFeed = async () => { try { const r = await fetch('/api/feed', { headers: await headers() }); if (!r.ok) return; const data = await r.json(); setUnseenActivity(data.filter((e: any) => !e.seen_at).length); setFeed(data.map((e: any) => ({ id: e.id, symbol: e.symbol, time: new Date(e.timestamp).toLocaleString(), title: e.title, text: e.reason, score: e.importance, source: e.evidence?.[0]?.source, verified: e.verified, tag: e.importance >= 90 ? 'High attention' : 'Worth a look' }))) } catch { /* use the transparent demo feed */ } }
  const markActivitySeen = async () => { setUnseenActivity(0); try { await fetch('/api/feed/seen', { method: 'POST', headers: await headers() }) } catch { /* UI remains read; next API refresh will reconcile. */ } }
  const loadNotifications = async () => { try { const r = await fetch('/api/notifications', { headers: await headers() }); if (!r.ok) return; setNotifications(await r.json()) } catch { setNotifications([]) } }
  const openNotifications = async () => { setShowNotifications(!showNotifications); if (!showNotifications) { await loadNotifications(); await fetch('/api/notifications/read', { method: 'POST', headers: await headers() }) } }
  useEffect(() => { if (!auth) { loadWatchlist(); loadFeed(); return }; return onAuthStateChanged(auth, value => { setUser(value); setAuthResolved(true) }) }, [])
  useEffect(() => { localStorage.setItem('market-memory-watchlist', JSON.stringify(watchlist)) }, [watchlist])
  useEffect(() => { loadWatchlist(); loadFeed() }, [user])
  const loadDiscover = async () => { try { const r = await fetch('/api/discover', { headers: await headers() }); if (!r.ok) throw new Error(); const data = await r.json(); setDiscoverStocks({ similar: (data.similar || []).map(stockFromApi), explore: (data.explore || []).map(stockFromApi) }) } catch { setDiscoverStocks({ similar: allStocks.slice(1, 3), explore: allStocks.slice(3) }) } }
  useEffect(() => { if (tab === 'discover') loadDiscover() }, [tab, user])
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('market-memory-theme', dark ? 'dark' : 'light') }, [dark])
  const openStock = async (stock: Stock) => { try { const r = await fetch(`/api/stocks/${encodeURIComponent(stock.symbol)}`, { headers: await headers() }); if (!r.ok) throw new Error(); const data = await r.json(); setStockDetail({ stock: stockFromApi(data), history: data.history || [] }) } catch { setStockDetail({ stock, history: stock.spark.map((price, i) => ({ time: String(i), price })) }) } }
  useEffect(() => { const timer = setTimeout(async () => { if (search.trim().length < 2) { setFiltered([]); setSearchMessage(''); return }; setSearchMessage('Searching live market…'); try { const r = await fetch(`/api/search?q=${encodeURIComponent(search)}`, { headers: await headers() }); if (!r.ok) throw new Error(); const data = await r.json(); const results = data.map(stockFromApi); if (!results.length) throw new Error(); setFiltered(results); setSearchMessage('') } catch { const results = allStocks.filter(s => `${s.symbol} ${s.name}`.toLowerCase().includes(search.toLowerCase())); setFiltered(results); setSearchMessage(results.length ? 'Showing reliable local results while live search reconnects.' : 'No matching stock found. Try TCS, INFY, HDFC, Reliance, or Tata.') } }, 250); return () => clearTimeout(timer) }, [search, user])
  const addStock = async (stock: Stock) => { if (!watchlist.some(s => s.symbol === stock.symbol)) setWatchlist(current => [...current, stock]); setSearch(''); setNotice(`${stock.symbol} added to your watchlist.`); try { const r = await fetch('/api/watchlist', { method: 'POST', headers: await headers(), body: JSON.stringify({ symbol: stock.symbol }) }); if (r.ok) await loadWatchlist(); else throw new Error() } catch { setNotice(`${stock.symbol} saved locally. We’ll sync it when the API is available.`) } }
  const removeStock = async (symbol: string) => { const old = watchlist; setWatchlist(old.filter(s => s.symbol !== symbol)); try { const r = await fetch(`/api/watchlist/${encodeURIComponent(symbol)}`, { method: 'DELETE', headers: await headers() }); if (!r.ok && apiReady) setWatchlist(old) } catch { if (apiReady) setWatchlist(old) } }
  async function explain(event: Event) {
    setExplaining(true); setExplanation('')
    try {
      const res = await fetch('/api/explain', { method: 'POST', headers: await headers(), body: JSON.stringify({ event, question }) })
      const data = await res.json(); if (!res.ok) throw new Error(data.error || 'The evidence assistant is temporarily unavailable.'); setExplanation(data.answer)
    } catch (error) {
      setExplanation(question ? (error instanceof Error ? error.message : 'The evidence assistant is temporarily unavailable.') : (event.verified ? 'Verified source links and timestamps are available above. Type a specific question to use the evidence assistant.' : 'There is no verified catalyst to explain yet. We deliberately do not speculate or generate an explanation until reliable evidence is available.'))
    } finally { setExplaining(false) }
  }
  if (!enteredApp) return <div className="login-screen"><div className="login-card"><div className="brand"><span className="brand-mark">g</span><span>groww</span></div><p className="eyebrow">SMART MARKET WATCHLIST</p><h1>{authResolved && user ? `Welcome back, ${user.displayName?.split(' ')[0] || 'Investor'}.` : 'Welcome back.'}</h1><p>See meaningful market changes with evidence—not noise.</p><button disabled={!authResolved} onClick={async()=>{ try { setSignInError(''); if (!auth) throw new Error('Firebase is not configured. Restart Vite after completing VITE_FIREBASE values in .env.'); if (!auth.currentUser) await signInWithPopup(auth, googleProvider); setEnteredApp(true) } catch (error) { setSignInError(error instanceof Error ? error.message : 'Google sign-in was blocked. Check Firebase Authorized domains.') } }}>{authResolved ? (user ? 'Open your watchlist' : 'Continue with Google') : 'Checking secure session…'}</button>{!firebaseEnabled && <small>Firebase browser configuration is missing. Add the four VITE_FIREBASE values and restart the frontend.</small>}{signInError && <small>{signInError}</small>}</div></div>
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">g</span><span>groww</span></div><nav>
      <button className={tab === 'watchlist' ? 'active' : ''} onClick={() => setTab('watchlist')}><Bookmark size={19}/> Watchlist</button>
      <button className={tab === 'away' ? 'active' : ''} onClick={() => { setTab('away'); markActivitySeen() }}><Sparkles size={19}/> While you were away {unseenActivity > 0 && <i>{unseenActivity}</i>}</button>
      <button className={tab === 'discover' ? 'active' : ''} onClick={() => setTab('discover')}><Compass size={19}/> Discover</button>
    </nav><div className="sidebar-bottom"><button onClick={()=>setShowHelp(true)}><CircleHelp size={19}/> Help & support</button><button onClick={()=>setTab('profile')}><Settings size={19}/> Settings</button><button className="user" onClick={() => setTab('profile')}><div className="avatar">{user?.displayName?.[0] || 'A'}</div><span><b>{user?.displayName || 'Demo investor'}</b><small>{firebaseEnabled ? (user ? 'Signed in' : 'Sign in to sync') : 'Demo mode'}</small></span>{firebaseEnabled && !user ? <em className="signin">Sign in</em> : <MoreHorizontal size={18}/>}</button>{signInError && <p className="auth-error">{signInError}</p>}</div></aside>
    <main><header><div><p className="eyebrow">FRIDAY, 4 SEPTEMBER</p><h1>{tab === 'watchlist' ? 'Your watchlist' : tab === 'away' ? 'While you were away' : tab === 'discover' ? 'Discover markets' : 'Your profile'}</h1></div><div className="header-actions"><button className="theme-toggle" onClick={()=>setDark(!dark)} title="Toggle theme">{dark ? <Sun size={18}/> : <Moon size={18}/>}</button><button className="refresh" onClick={loadWatchlist} disabled={loading}>{loading ? 'Refreshing…' : 'Refresh'}</button><span className="updated"><span/> Updated just now</span><button className="bell" onClick={openNotifications}><Bell size={20}/>{notifications.some(n=>n.status==='UNREAD') && <em/>}</button>{showNotifications && <div className="notification-panel"><div className="notification-title"><b>Notifications</b><button onClick={()=>setShowNotifications(false)} aria-label="Close notifications"><X size={15}/></button></div>{notifications.length ? notifications.map(n=><div key={n.id}><strong>{n.symbol}</strong><span>{n.title}</span></div>) : <p>No attention-triggered notifications yet.</p>}</div>}</div></header>{notice && <div className="notice">{notice}<button onClick={()=>setNotice('')}><X size={14}/></button></div>}
      {tab === 'watchlist' && <><section className="summary"><div><span className="mini-label">WATCHLIST VALUE</span><strong>₹10.22L</strong><small className="gain"><TrendingUp size={14}/> ₹14,872 today</small></div><div className="summary-divider"/><div><span className="mini-label">MARKET MOOD</span><strong>Positive <span className="mood-dot"/></strong><small>68% stocks are advancing</small></div><div className="summary-art"><div className="orb orb1"/><div className="orb orb2"/><TrendingUp size={60}/></div></section>
      <section className="watch-head"><div><h2>Stocks you follow</h2><p>Meaningful moves, not noisy ticks.</p></div><div className="searchbox"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search real stocks"/>{search && <button onClick={()=>setSearch('')}><X size={16}/></button>} {search && <div className="search-results">{searchMessage && <p className="search-status">{searchMessage}</p>}{filtered.map(s => <button key={s.symbol} onClick={() => addStock(s)}><span><b>{s.symbol}</b><small>{s.name}</small></span>{watchlist.some(x=>x.symbol===s.symbol) ? <small>Added</small> : <Plus size={18}/>}</button>)}</div>}</div></section>
      <section className="stock-grid">{watchlist.map(stock => <article className="stock-card" key={stock.symbol} onClick={()=>openStock(stock)}><div className="stock-top"><div><b>{stock.symbol}</b><span>{stock.name}{stock.delayed ? ' · Data delayed' : ''}</span></div><button className="more" onClick={(e) => { e.stopPropagation(); removeStock(stock.symbol) }} title="Remove from watchlist"><MoreHorizontal size={19}/></button></div><div className="stock-bottom"><div><strong><Rupee value={stock.price}/></strong><span className={stock.change >= 0 ? 'gain' : 'loss'}>{stock.change >= 0 ? '+' : ''}{stock.change}% today</span></div><Sparkline values={stock.spark} color={stock.change >= 0 ? '#00a77c' : '#dd675d'}/></div>{feed.some(e=>e.symbol===stock.symbol && e.score>=70) && <button className="attention" onClick={(e)=>{e.stopPropagation();setSelected(feed.find(e=>e.symbol===stock.symbol) || null); setExplanation('')}}><span/> {feed.find(e=>e.symbol===stock.symbol)?.tag}<ChevronRight size={15}/></button>}</article>)}</section>
      <section className="trust-strip"><div className="trust-icon">✓</div><div><b>Built for clarity, not noise.</b><span>We only explain moves with verified evidence. When we don’t know, we say so.</span></div><button onClick={()=>setTab('away')}>See activity <ChevronRight size={16}/></button></section></>}
      {tab === 'away' && <section className="feed"><div className="feed-intro"><span className="green-circle"><Sparkles size={19}/></span><div><h2>{feed.length} things changed since your last visit</h2><p>Here’s the signal, with the evidence behind it.</p></div></div>{feed.length === 0 && <div className="empty-state"><Sparkles size={26}/><h2>No meaningful changes yet</h2><p>Add a stock, then press Refresh. We create an activity event only when a price movement is worth surfacing.</p><button onClick={()=>setTab('watchlist')}>Go to watchlist</button></div>}{feed.map(event => <article className="event-card" key={event.id}><div className="timeline"><span className={event.score >= 90 ? 'hot' : event.verified ? 'warm' : 'cool'}/><i/></div><div className="event-content"><div className="event-meta"><span>{event.time}</span><span className={event.verified ? 'verified' : 'pending'}>{event.verified ? '✓ Verified' : '⌛ Verifying'}</span></div><div className="event-title"><div className="symbol-badge">{event.symbol.slice(0,2)}</div><div><h3>{event.title}</h3><p>{event.text}</p></div></div><div className="event-foot"><span className="score"><b>{event.score}</b>/100 attention score</span>{event.source && <span className="source">{event.source}</span>}<button onClick={()=>{setSelected(event); setExplanation('')}}>Understand this <ChevronRight size={16}/></button></div></div></article>)}</section>}
      {tab === 'discover' && <section className="discover"><div className="discover-hero"><p className="eyebrow">EXPLORE, DON’T FOLLOW BLINDLY</p><h2>Ideas around your interests.</h2><p>Live prices with transparent reasons for discovery. These are research prompts, never buy/sell advice.</p></div><div className="discover-title"><h2>Explore securities</h2><div className="searchbox"><Search size={17}/><input value={discoverQuery} onChange={e=>setDiscoverQuery(e.target.value)} placeholder="Filter discover"/></div></div>{[['Similar to your watchlist', discoverStocks.similar], ['Market exploration', discoverStocks.explore]].map(([title, items]) => { const matches = (items as Stock[]).filter(stock => `${stock.name} ${stock.symbol}`.toLowerCase().includes(discoverQuery.toLowerCase())); return <div className="discover-section" key={title as string}><h3>{title as string}</h3><p>{title === 'Similar to your watchlist' ? 'Comparable sector peers based on the securities you follow.' : 'A balanced set of active Indian-market sectors to research.'}</p><div className="discover-grid">{matches.map(stock=>{ const added = watchlist.some(item => item.symbol === stock.symbol); return <article key={stock.symbol} onClick={()=>openStock(stock)}><div className="circle-logo">{stock.symbol[0]}</div><span>{stock.reason || 'Market exploration'}</span><b>{stock.name}</b><small>{stock.symbol}</small><strong><Rupee value={stock.price}/></strong><small className={stock.change>0?'gain':'loss'}>{stock.change>0?'+':''}{stock.change}% today</small><button className={added ? 'added-button' : ''} disabled={added} onClick={(e)=>{e.stopPropagation();if (!added) addStock(stock)}}>{added ? '✓ In your watchlist' : <><Plus size={16}/> Add to watchlist</>}</button></article>})}</div></div>})}</section>}
      {tab === 'profile' && <section className="profile-page"><div className="profile-card"><div className="profile-avatar">{user?.displayName?.[0] || 'A'}</div><div><h2>{user?.displayName || 'Demo investor'}</h2><p>{user?.email || 'Sign in with Google to sync your watchlist securely.'}</p></div>{firebaseEnabled && !user && <button className="profile-signin" onClick={async()=>{try { if (auth) await signInWithPopup(auth, googleProvider) } catch { setSignInError('Google sign-in was blocked. Add localhost to Firebase Authorized domains.') }}}>Sign in with Google</button>}</div><div className="profile-settings"><h2>Settings</h2><label><span>Dark mode</span><input type="checkbox" checked={dark} onChange={e=>setDark(e.target.checked)} /></label><label><span>Meaningful price moves</span><input type="checkbox" defaultChecked onChange={e=>fetch('/api/profile/preferences',{method:'PATCH',headers:{'Content-Type':'application/json','X-Demo-User':'demo-user'},body:JSON.stringify({notify_moves:e.target.checked})})}/></label><label><span>Verified company events</span><input type="checkbox" defaultChecked /></label><button className="logout" onClick={()=>{auth && signOut(auth); setEnteredApp(false)}}><LogOut size={16}/> Log out</button></div></section>}
    </main>
    {stockDetail && <div className="modal-wrap" onMouseDown={()=>setStockDetail(null)}><aside className="explain-panel stock-panel" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setStockDetail(null)}><X size={21}/></button><span className="eyebrow">LIVE MARKET DETAIL · 1 MONTH</span><h2>{stockDetail.stock.name}</h2><p className="stock-symbol">{stockDetail.stock.symbol}</p><strong className="detail-price"><Rupee value={stockDetail.stock.price}/></strong><p className={stockDetail.stock.change >= 0 ? 'gain' : 'loss'}>{stockDetail.stock.change >= 0 ? '+' : ''}{stockDetail.stock.change.toFixed(2)}% today</p><div className="detail-chart"><PriceHistoryChart history={stockDetail.history} change={stockDetail.stock.change}/></div><div className="detail-metrics"><span><b>{stockDetail.history.length}</b> trading days</span><span><b>{stockDetail.stock.delayed ? 'Delayed' : 'Live'}</b> market data</span></div><p className="modal-copy">Current price and historical scale come from the configured market provider. Event reasons appear in the activity feed only after dated evidence is found.</p>{watchlist.some(item=>item.symbol===stockDetail.stock.symbol) ? <button className="explain-btn added-detail" disabled>✓ In your watchlist</button> : <button className="explain-btn" onClick={()=>addStock(stockDetail.stock)}><Plus size={18}/> Add to watchlist</button>}</aside></div>}
    {selected && <div className="modal-wrap" onMouseDown={()=>setSelected(null)}><aside className="explain-panel" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X size={21}/></button><span className="eyebrow">EVENT BREAKDOWN</span><h2>{selected.title}</h2><p className="modal-copy">{selected.text}</p><div className={selected.verified ? 'evidence verified-box' : 'evidence pending-box'}><b>{selected.verified ? 'Verified evidence' : 'No verified reason yet'}</b><span>{selected.verified ? `${selected.source}. We use reliable, timestamped sources before drawing a connection.` : 'We’re monitoring trusted sources and will update this event when evidence becomes available.'}</span></div><label className="question-label">Ask about this evidence<input value={question} onChange={e=>setQuestion(e.target.value)} maxLength={180} placeholder="e.g. What was announced?"/></label><button className="explain-btn" onClick={()=>explain(selected)} disabled={explaining}>{explaining ? 'Checking verified evidence…' : <><Sparkles size={18}/> {question ? 'Ask verified evidence' : 'Show what we know'}</>}</button>{explanation && <div className="answer"><b>What we know</b><p>{explanation}</p><small>{question ? 'Generated only for your question from saved evidence.' : 'No LLM used. Ask a follow-up only if you need it.'} Not investment advice.</small></div>}</aside></div>}
    {showHelp && <div className="modal-wrap" onMouseDown={()=>setShowHelp(false)}><aside className="explain-panel" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowHelp(false)}><X size={21}/></button><span className="eyebrow">HELP & SUPPORT</span><h2>How Market Memory works</h2><div className="help-item"><b>Why an event is shown</b><p>We flag meaningful price movements, then attach dated evidence when reliable coverage is available.</p></div><div className="help-item"><b>Why an event may have no reason</b><p>We do not guess. The event updates only after verified evidence is stored.</p></div><div className="help-item"><b>Need assistance?</b><p>For the hackathon demo, email support@marketmemory.demo with the event symbol and time.</p></div></aside></div>}
  </div>
}
createRoot(document.getElementById('root')!).render(<App />)
